version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: catsgram       # Изменил filmsdb → catsgram
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint: |
      - bash
      - -c
      - |
        set -e
        psql -v ON_ERROR_STOP=1 "postgresql://dbuser:12345@db:5432/catsgram" <<-EOSQL
          CREATE TABLE IF NOT EXISTS cats (
              id SERIAL PRIMARY KEY,
              name VARCHAR(50) NOT NULL,
              breed VARCHAR(50),
              age INTEGER
          );
          INSERT INTO cats (name, breed, age) VALUES
              (''Whiskers'', ''Siamese'', 3),
              (''Tom'', ''Tabby'', 5),
              (''Luna'', ''Persian'', 2);
      EOSQL'